/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;


import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Ticket Booking Application");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try {
            userBookingService = new UserBookingService();
        }catch (IOException ex){
            System.out.println("There is something wrong " );
            return;

        }

        while (option!=7){
            System.out.println("Choose option");
            System.out.println("1. sign up");
            System.out.println("2.Login");
            System.out.println("3.Fetch Booking");
            System.out.println("4.Search Trains");
            System.out.println("5.Book a seat");
            System.out.println("6.Cancle my Booking");
            System.out.println("7.Exit the app");
            option=scanner.nextInt();
            switch (option){
                case 1:
                    System.out.println("Enter the username to Signup");
                    String nameToSignUp=scanner.next();
                    System.out.println("Enter the Password to Signup");
                    String passwordToSignUp=scanner.next();
                    User userToSignup=new User(nameToSignUp, passwordToSignUp,
                            UserServiceUtil.hashPassword(passwordToSignUp),
                             new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignup);
                    break;

                 case 2:
                     System.out.println("Enter the username to Login");
                     String nameToLogin =scanner.next();
                     System.out.println("Enter the Password to Login ");
                     String passwordToLogin= scanner.next();
                     User userToLogin=new User(nameToLogin,passwordToLogin,
                             UserServiceUtil.hashPassword(passwordToLogin),
                             new ArrayList<>(),UUID.randomUUID().toString());
                     try {
                         userBookingService=new UserBookingService(userToLogin);
                     }catch (IOException ex){
                         return;
                     }
                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fectchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    String source = scanner.next();
                    System.out.println("Type your destination station");
                    String destination= scanner.next();
                    List<Train> trains=userBookingService.getTrains(source,destination);
                    int index = 1;
                    for (Train t: trains){
                        System.out.println(index+" Train id : "+t.getTrainId());
                        for (Map.Entry<String, String> entry: t.getStationTimes().entrySet()){
                            System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    trainSelectedForBooking = trains.get(scanner.nextInt());
                    break;

                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row: seats){
                        for (Integer val: row){
                            System.out.print(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = scanner.nextInt();
                    System.out.println("Enter the column");
                    int col = scanner.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! Enjoy your journey");
                    }else{
                        System.out.println("Can't book this seat");
                    }
                    break;
                default:
                    break;
            }
            }
        }


    }
}
